### pandas --> python library
### anlayzing,cleaning, exploring,manipuating data

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Megha Daniel\Documents\DataAnalysis\Python\venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Megha Daniel\Documents\DataAnalysis\Python\venv\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Megha Daniel\Documents\DataAnalysis\Python\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Megha Daniel\Documents\DataAnalysis\Python\venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\Megha Daniel\Documents\DataAnalysis\Python\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import pandas as pd
from numpy.random import randn

1. Series ---> 1 D
2. DataFrames --> 2D(series gp)
3. Panals

In [ ]:
#SERIES
my_list = [1,2,3,4,5]
pd.Series(my_list)

fruits =["apple","cherry","Orange"]
pd.Series(fruits)

fruits =["apple","cherry","Orange"]
pd.Series(data=fruits)

In [5]:
my_list = [10,20,30]
labels = ['a','b','c']

print(pd.Series(data=my_list,index=labels))


print(pd.Series(my_list,labels))

print(pd.Series(labels,my_list))

a    10
b    20
c    30
dtype: int64
a    10
b    20
c    30
dtype: int64
10    a
20    b
30    c
dtype: str

In [8]:
## Using an Index
ser1 = pd.Series([1,2,3,4],index=['USA','Germany','USSR','Japan'])
print(ser1)
print("-------------")

ser2 = pd.Series([1,2,5,4],index=['USA','Germany','Italy','Japan'])
print(ser2)
print("-------------")

print(ser1['USA'])
print("--------------")


print(ser1 +ser2)

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64
-------------
USA        1
Germany    2
Italy      5
Japan      4
dtype: int64
-------------
1
--------------
Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [9]:
person = {"name":["helna","Jeethu","Jithu","Miya","john"],
          "age" : [20,25,22,28,30],
          "place":["EKM","KTM","TVM","EKM","KZD"]
         }
person

{'name': ['helna', 'Jeethu', 'Jithu', 'Miya', 'john'],
 'age': [20, 25, 22, 28, 30],
 'place': ['EKM', 'KTM', 'TVM', 'EKM', 'KZD']}

In [13]:
# load this json to DataFrame object

df = pd.DataFrame(person, index = [1,2,3,4,5])

print(df)

df

     name  age place
1   helna   20   EKM
2  Jeethu   25   KTM
3   Jithu   22   TVM
4    Miya   28   EKM
5    john   30   KZD

     name  age place
1   helna   20   EKM
2  Jeethu   25   KTM
3   Jithu   22   TVM
4    Miya   28   EKM
5    john   30   KZD

In [2]:
df_rand = pd.DataFrame(randn(5,4))
df_rand

          0         1         2         3
0  1.043045 -0.429418  2.009925 -0.776352
1 -0.841583 -0.057375  0.702141  0.433571
2 -0.352269  0.314587 -1.388361  0.698675
3 -0.592135  0.716669 -0.149443 -0.844523
4 -0.309816  0.736600  1.850437 -0.047284

In [ ]:
# df_rand =pd.DataFrame(randn(5,4),index=['A','B','C','D','E'],columns=['W' , 'X', 'Y', 'Z'])

# df_rand =pd.DataFrame(randn(5,4),index=['A','B','C','D','E'],columns=['W X Y Z'.split()])

# split function itself will return a list and putting agin it in a list will result in multiindex and 
# make it difficult to do 
# above code shows error:  https://chatgpt.com/c/6adcbb69-0830-83ee-b660-bcf5c5537bf7


df_rand =pd.DataFrame(randn(5,4),index=['A','B','C','D','E'],columns='W X Y Z'.split())
df_rand

          W         X         Y         Z
A -0.068122 -0.858692 -2.392935  0.185064
B -0.217922 -0.382783 -1.174613 -0.193835
C -1.082835 -0.317061 -0.199071  1.205256
D -0.277324  0.884268 -1.395603  1.859963
E -0.514612 -1.240486  1.011331 -0.552255

In [18]:
### Selction and Indexing

print(df_rand['W'])

print(df_rand[['W','Y']])

          W
A -0.449484
B  1.310167
C -0.063199
D  0.150543
E -1.343673
          W         Y
A -0.449484  0.723293
B  1.310167  0.135615
C -0.063199  1.102470
D  0.150543 -0.167141
E -1.343673  1.979205

In [20]:
print(type(df[['name','place']]))

print(type(df['name']))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

In [21]:
df_rand.W  # SQL syntax (not recommended)

          W
A -0.449484
B  1.310167
C -0.063199
D  0.150543
E -1.343673

In [30]:
df_rand['new'] = df_rand['W'] + df_rand['X']
df_rand

          W         X         Y         Z       new
A -0.068122 -0.858692 -2.392935  0.185064 -0.926814
B -0.217922 -0.382783 -1.174613 -0.193835 -0.600704
C -1.082835 -0.317061 -0.199071  1.205256 -1.399896
D -0.277324  0.884268 -1.395603  1.859963  0.606944
E -0.514612 -1.240486  1.011331 -0.552255 -1.755098

In [27]:
print(df_rand.columns)

MultiIndex([('W',),
            ('X',),
            ('Y',),
            ('Z',)],
           )

### dropping columns

##### axis = 1 for columns

In [32]:
df['colors'] = ['red','blue','green','cyan','yellow']
df

     name  age place  colors
1   helna   20   EKM     red
2  Jeethu   25   KTM    blue
3   Jithu   22   TVM   green
4    Miya   28   EKM    cyan
5    john   30   KZD  yellow

In [ ]:

df.drop('colors',axis= 1)
print("---------------")
df.drop('colors',axis= 1,inplace=True)
print("---------------")
df = df.drop('colors',axis= 1)
print("---------------")

KeyError: "['colors'] not found in axis"

## drop rows

In [33]:
df_rand.drop("E",axis=0)

          W         X         Y         Z       new
A -0.068122 -0.858692 -2.392935  0.185064 -0.926814
B -0.217922 -0.382783 -1.174613 -0.193835 -0.600704
C -1.082835 -0.317061 -0.199071  1.205256 -1.399896
D -0.277324  0.884268 -1.395603  1.859963  0.606944

In [35]:
df_rand

          W         X         Y         Z       new
A -0.068122 -0.858692 -2.392935  0.185064 -0.926814
B -0.217922 -0.382783 -1.174613 -0.193835 -0.600704
C -1.082835 -0.317061 -0.199071  1.205256 -1.399896
D -0.277324  0.884268 -1.395603  1.859963  0.606944
E -0.514612 -1.240486  1.011331 -0.552255 -1.755098

### Locating Rows : loc

##### based on label

In [ ]:
df_rand.loc["A"] # LOC ---: selection based on Label

### Locating Rows : iloc

##### based on index

In [36]:
df_rand.iloc[2] # iLOC ---: selection based on index

W     -1.082835
X     -0.317061
Y     -0.199071
Z      1.205256
new   -1.399896
Name: C, dtype: float64

In [ ]:
print(df_rand.loc[['A','B'],['W','Y']])

print(df_rand.loc[['A','B']])


# print(df_rand.loc['W','Y']) # error since its column

print(df_rand.iloc[1,2]) # 2nd row 3rd column

          W         Y
A -0.068122 -2.392935
B -0.217922 -1.174613
          W         X         Y         Z       new
A -0.068122 -0.858692 -2.392935  0.185064 -0.926814
B -0.217922 -0.382783 -1.174613 -0.193835 -0.600704
-1.174613318607848

In [51]:
# age > 20

df[df['age']>20]['name']

2    Jeethu
3     Jithu
4      Miya
5      john
Name: name, dtype: str

In [52]:
df_rand[(df_rand['W']>0) &(df_rand["Y"]<0.5)]

Empty DataFrame
Columns: [W, X, Y, Z, new]
Index: []

In [53]:
df[df['age']<25][['name','place']]

    name place
1  helna   EKM
3  Jithu   TVM

## Index

In [3]:
df_rand.reset_index()

   index         0         1         2         3
0      0  1.043045 -0.429418  2.009925 -0.776352
1      1 -0.841583 -0.057375  0.702141  0.433571
2      2 -0.352269  0.314587 -1.388361  0.698675
3      3 -0.592135  0.716669 -0.149443 -0.844523
4      4 -0.309816  0.736600  1.850437 -0.047284

In [5]:
newind = ['CA','NY','WY','OR','CO']
df_rand['States'] = newind
df_rand

          0         1         2         3 States
0  1.043045 -0.429418  2.009925 -0.776352     CA
1 -0.841583 -0.057375  0.702141  0.433571     NY
2 -0.352269  0.314587 -1.388361  0.698675     WY
3 -0.592135  0.716669 -0.149443 -0.844523     OR
4 -0.309816  0.736600  1.850437 -0.047284     CO

In [6]:
df_rand.set_index('States')

               0         1         2         3
States
CA      1.043045 -0.429418  2.009925 -0.776352
NY     -0.841583 -0.057375  0.702141  0.433571
WY     -0.352269  0.314587 -1.388361  0.698675
OR     -0.592135  0.716669 -0.149443 -0.844523
CO     -0.309816  0.736600  1.850437 -0.047284

## Missing Values

In [4]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [9]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [10]:
# drop nan columns
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [11]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(thresh=2)

# atleast 2 non NAN

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

### FILL VALUE

In [7]:
df.fillna(value="FILL VALUE")

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [ ]:
# fill the NAN values in "A" column 
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

### EDA

The groupby method allows you to group rows of data together and call aggregate functions

In [9]:
# Create dataframe
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)

In [11]:
by_comp = df.groupby('Company')['Sales'].mean()
print(by_comp)

grp_median = df.groupby('Company')['Sales'].median()
print(grp_median)

Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64
Company
FB      296.5
GOOG    160.0
MSFT    232.0
Name: Sales, dtype: float64

In [13]:
df.groupby('Company')['Sales'].std()

Company
FB       75.660426
GOOG     56.568542
MSFT    152.735065
Name: Sales, dtype: float64

#### describe() : for stat analysis

In [14]:
df.describe()

            Sales
count    6.000000
mean   229.500000
std    100.899455
min    120.000000
25%    143.000000
50%    221.500000
75%    315.750000
max    350.000000

In [15]:
df.groupby('Company').describe()

        Sales
        count   mean         std    min     25%    50%     75%    max
Company
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [16]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

## DATA WRANGLING

Merging, Joining, and Concatenating¶

In [17]:
df1 = pd.DataFrame({    'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({    'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({    'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

print(df1)
print(df2)
print(df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

## Concatenation

    Concatenation basically glues together DataFrames. Keep in mind that dimensions should match along the axis you are concatenating on. You can use pd.concat and pass in a list of DataFrames to concatenate together:

In [18]:
pd.concat([df1,df2,df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [19]:
pd.concat([df1,df2,df3],axis=1)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [20]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

## Merging

The merge function allows you to merge DataFrames together using a similar logic as merging SQL Tables together. For example:

In [21]:
pd.merge(left,right,how='left',on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [22]:
pd.merge(left,right,how='inner',on='key')

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [25]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})
print(left)
print("-------------")
print(right)

  key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3
-------------
  key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

## Joining

Joining is a convenient method for combining the columns of two potentially differently-indexed DataFrames into a single result DataFrame.

In [27]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
left.join(right)

In [ ]:
left.join(right,how='outer')

#### *concant == same feature
#### *merge == analysis based on one feature
#### *join == same inddex but different columns

# Operations

In [29]:
df = pd.DataFrame({'col1':[1,2,3,4,5,6,7],'col2':[444,555,666,444,777,888,444],'col3':['abc','def','ghi','xyz','wxy','hij','def']})

In [31]:
df.head() # first 5

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz
4     5   777  wxy

In [32]:
df.tail()

   col1  col2 col3
2     3   666  ghi
3     4   444  xyz
4     5   777  wxy
5     6   888  hij
6     7   444  def

In [ ]:
df.sample() # default in sample : 1

   col1  col2 col3
4     5   777  wxy

In [34]:
df.sample(3)

   col1  col2 col3
3     4   444  xyz
5     6   888  hij
2     3   666  ghi

### Info on Unique Values

In [35]:
print(df['col2'].unique())

[444 555 666 777 888]

In [37]:
print(df['col2'].nunique())

5

In [38]:
print(df['col2'].value_counts())

col2
444    3
555    1
666    1
777    1
888    1
Name: count, dtype: int64

In [39]:
# selecting df

df[(df['col1']>3) & (df['col2']==444)]

   col1  col2 col3
3     4   444  xyz
6     7   444  def

### Applying Functions

In [ ]:

def times2(x):
    return x*2

In [41]:
df['col1'].apply(times2)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
Name: col1, dtype: int64

In [42]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
4    3
5    3
6    3
Name: col3, dtype: int64

In [ ]:
df['col1'].sum()

np.int64(28)

### apply() vs sum()

#  Permanently Removing a Column

In [44]:
del df['col1']

In [45]:
print(df.columns)

Index(['col2', 'col3'], dtype='str')

In [46]:
df.index

RangeIndex(start=0, stop=7, step=1)

In [47]:
df.sort_values(by='col2')

   col2 col3
0   444  abc
3   444  xyz
6   444  def
1   555  def
2   666  ghi
4   777  wxy
5   888  hij

### ** Find Null Values or Check for Null Values**

In [48]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False

In [49]:
df.isnull().sum()

col2    0
col3    0
dtype: int64

In [50]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

## 'FILL'

In [51]:
df.fillna("FILL")

   col1   col2 col3
0   1.0   FILL  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  FILL  444.0  xyz

In [53]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

### multi variable analysis

In [54]:
df.pivot_table(values='D',index=['A','B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN